name: Deploy Demo

on:
  push:
    branches:
      - main
    paths:
      - packages/runnable-app/**

jobs:
  deploy:
    name: 🚀 Deploy Demo
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🪰 Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: 🚀 Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
