name: Deploy Docs

on:
  push:
    branches:
      - main
    paths:
      - docs/**

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

      - uses: actions/configure-pages@v2

      - run: pnpm install  --frozen-lockfile

      - name: Build docs 📚
        run: pnpm docs:build

      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy 🚀
        id: deployment
        uses: actions/deploy-pages@v1
